### ISSUE TITLE
Implementar uma GUI?

### ISSUE THREAD

**Issue by matheuszinn** [Matheuszinn/Praticas-Processamento-de-Imagens#1]
Agora no início tá tranquilo usando o pyinquirer, mas acho q a medida que mais funcionalidades forem implementadas, vai ficar mais complexo de manter um CLI, entretanto, o mesmo vale para uma GUI.
Eh mole kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk[](url)

**Comment by thaisclxt** [comment]
dakshfbkhasnkfjs, realmente. podemos ir vendo a necessidade e implementando ao longo do projeto
