### ISSUE TITLE
Wrong Boundaries

### ISSUE THREAD

**Issue by h80r** [Matheuszinn/Praticas-Processamento-de-Imagens#2]
https://github.com/Matheuszinn/Praticas-Processamento-de-Imagens/blob/2dc86e5948bc35e46684791298e8ba764ff0551f/simpleImage.py#L40

`y` needs to reference the height axis.
Try with images where X axis != Y axis.

```bash
❯ py main.py
? O que deseja fazer com a imagem ?  Interpolação
? Por qual método você deseja realizar a interpolação?  Vizinho mais próximo
? Escolha o tipo de interpolação:   Ampliação
? Você deseja salvar a imagem resultante ?  Yes
Traceback (most recent call last):
  File "/home/h80r/Downloads/Praticas-Processamento-de-Imagens/main.py", line 54, in <module>
    handler.execute(
  File "/home/h80r/Downloads/Praticas-Processamento-de-Imagens/methodhandler.py", line 24, in execute
    self.metodos[vals[0]] \
  File "/home/h80r/Downloads/Praticas-Processamento-de-Imagens/simpleImage.py", line 55, in interpolacao_vizinhos_ampliacao
    row.append(self.pixel_data[x,y])
IndexError: image index out of range
```

Test image:
![ahegao](https://user-images.githubusercontent.com/60087690/117966273-1a6f4500-b2fa-11eb-8600-bf8aae93ffc7.png)

**Comment by matheuszinn** [comment]
thanks man, it was fixed. btw i've realized that the method that turns the image to grayscale isn't working as intended when the input is a image that is already in grayscale. eh mole
